### ISSUE TITLE
Criar usuário

### ISSUE THREAD

**Issue by tayh** [PI2-PLG/PLG-Profile#1]
**Descrição**
Criar a classe de usuário para receber as informações de login do front-end

**Tarefas**

- [ ] Model
- [ ] Receber requisições do front

**Critérios de Aceitação**

**Comment by lucassoaresouza** [comment]
Foi removida deste repositório para a API Gateway
[issue #3](https://github.com/PI2-PLG/PLG-APIGateway/issues/3)
